CREATE TABLE IF NOT EXISTS games (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    slug VARCHAR(170) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    price DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    original_price DECIMAL(10, 2) DEFAULT NULL,
    discount_percent TINYINT UNSIGNED NOT NULL DEFAULT 0,
    image_title VARCHAR(180) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    genre VARCHAR(80) NOT NULL,
    secondary_genre VARCHAR(80) DEFAULT NULL,
    rating DECIMAL(2, 1) NOT NULL DEFAULT 0.0,
    age_rating VARCHAR(20) NOT NULL DEFAULT 'PEGI 12',
    platform VARCHAR(120) NOT NULL DEFAULT 'PC',
    developer VARCHAR(120) NOT NULL,
    publisher VARCHAR(120) NOT NULL,
    release_date DATE NOT NULL,
    stock INT UNSIGNED NOT NULL DEFAULT 0,
    is_featured TINYINT(1) NOT NULL DEFAULT 0,
    is_new_release TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO games (
    title,
    slug,
    description,
    price,
    original_price,
    discount_percent,
    image_title,
    image_url,
    genre,
    secondary_genre,
    rating,
    age_rating,
    platform,
    developer,
    publisher,
    release_date,
    stock,
    is_featured,
    is_new_release
) VALUES
('Plumber from Italy: Pipe Kingdom', 'plumber-from-italy-pipe-kingdom', 'A colorful platform adventure about a brave plumber who travels through pipe-filled kingdoms to rescue a mushroom realm from a fiery ruler. Players jump across moving traps, collect coins, unlock secret routes, and meet cheerful characters in every world. It is built for fans of quick levels, local co-op, and classic arcade-style fun.', 39.99, 49.99, 20, 'Plumber from Italy cover art', 'assets/images/games/plumber-from-italy-pipe-kingdom.jpg', 'Platformer', 'Adventure', 4.8, 'PEGI 7', 'PC, Nintendo-style handheld', 'Pasta Pixel Studio', 'JumpBox Publishing', '2024-03-15', 120, 1, 0),
('Blockcraft Survival', 'blockcraft-survival', 'An open sandbox world made of blocks, crafting, mining, farming, and dangerous nights. You can build castles, underground bases, automated farms, or entire cities while surviving monsters, weather, and deep caves. The game includes creative mode, survival mode, online servers, and endless space for experimenting with your own ideas.', 24.99, NULL, 0, 'Blockcraft Survival cover art', 'assets/images/games/blockcraft-survival.jpg', 'Sandbox', 'Survival', 4.7, 'PEGI 7', 'PC, Xbox-style console, Mobile', 'CubeForge Labs', 'Indie Mineworks', '2023-11-09', 300, 1, 0),
('Grand Theft Auto-ish: Neon County', 'grand-theft-auto-ish-neon-county', 'A satirical open-world city action game full of fast cars, strange side businesses, and chaotic missions. Neon County lets you complete criminal jobs, race through traffic, buy properties, and wander through a city where every simple plan becomes a disaster. The story mixes dark comedy with dozens of optional activities outside the main campaign.', 59.99, 69.99, 14, 'Neon County cover art', 'assets/images/games/grand-theft-auto-ish-neon-county.jpg', 'Open World', 'Action', 4.6, 'PEGI 18', 'PC, PlayBox Series', 'Liberty Parody Works', 'Big Map Interactive', '2025-05-02', 75, 1, 1),
('Legend of Zeldo: Echo Woods', 'legend-of-zeldo-echo-woods', 'A fantasy adventure about a quiet hero searching for the lost voice of an ancient forest. Explore wide regions, solve temple puzzles, collect magical tools, and defeat bosses hidden behind old legends. The game is calm, mysterious, and focused on the feeling that every hill, cave, and ruin hides another secret.', 44.99, 59.99, 25, 'Echo Woods cover art', 'assets/images/games/legend-of-zeldo-echo-woods.jpg', 'Adventure', 'Puzzle', 4.9, 'PEGI 12', 'PC, Nintendo-style handheld', 'Green Tunic Games', 'TriSpark Media', '2024-09-20', 90, 1, 0),
('Call of Booty: Modern Shooty', 'call-of-booty-modern-shooty', 'A fast military FPS with short missions, online arenas, and a campaign that seems to explode every ten seconds. The game focuses on instant action, soldier classes, weapon customization, and multiplayer matches designed for quick intense sessions. Fans of arcade shooting will enjoy the pace, progression rewards, and large set of cosmetic unlocks.', 49.99, 69.99, 29, 'Modern Shooty cover art', 'assets/images/games/call-of-booty-modern-shooty.jpg', 'FPS', 'Action', 4.2, 'PEGI 18', 'PC, PlayBox Series, X-Cube', 'BoomSight Studios', 'Annual Ops Publishing', '2025-10-31', 140, 0, 1),
('Elden Onion', 'elden-onion', 'A dark action RPG with a huge world, strange bosses, and layered lore that may make you cry like an onion. Every region hides its own rules, dangerous enemies, secret dungeons, and equipment that can completely change your play style. The game is challenging but fair, especially for players who enjoy discovering story through environments and small details.', 54.99, 59.99, 8, 'Elden Onion cover art', 'assets/images/games/elden-onion.jpg', 'Action RPG', 'Soulslike', 4.9, 'PEGI 16', 'PC, PlayBox Series, X-Cube', 'Fromage Software', 'Golden Ring Co.', '2024-02-23', 65, 1, 0),
('The Last of Gus', 'the-last-of-gus', 'An emotional survival adventure about a tired guardian and a stubborn teenager crossing an overgrown post-apocalyptic world. The game combines tense stealth, limited resources, a strong story, and grounded encounters with both survivors and infected threats. Its biggest strength is the atmosphere of the journey and the difficult choices that never feel simple.', 47.99, 59.99, 20, 'The Last of Gus cover art', 'assets/images/games/the-last-of-gus.jpg', 'Story Adventure', 'Survival', 4.8, 'PEGI 18', 'PC, PlayBox Series', 'Nice Dog Studio', 'Cinematic Games Ltd.', '2023-08-18', 55, 1, 0),
('Fort Knight Build Royale', 'fort-knight-build-royale', 'A colorful battle royale where players shoot, build, glide, and dance across an island that keeps changing. Each season adds new weapons, events, locations, and cosmetics so players can create their own style. Matches are quick and easy to enter, but still leave room for skilled builders, clever teamwork, and last-second saves.', 0.00, NULL, 0, 'Fort Knight cover art', 'assets/images/games/fort-knight-build-royale.jpg', 'Battle Royale', 'Shooter', 4.1, 'PEGI 12', 'PC, Console, Mobile', 'Epic-ish Playground', 'Loop Storm Entertainment', '2025-01-12', 999, 0, 1),
('FIFA-ish Street 26', 'fifa-ish-street-26', 'A football simulator with almost-licensed teams, career mode, street matches, and an endless chase for better player cards. Alongside classic league play, it offers quick arcade modes, online tournaments, training challenges, and management decisions off the pitch. It works well for both one relaxed match and a full season played across many evenings.', 64.99, 74.99, 13, 'FIFA-ish Street 26 cover art', 'assets/images/games/fifa-ish-street-26.jpg', 'Sports', 'Football', 3.9, 'PEGI 3', 'PC, PlayBox Series, X-Cube', 'Almost Sports Studio', 'GoalNet Interactive', '2025-09-19', 180, 0, 1),
('Red Bread Redemption', 'red-bread-redemption', 'A western open-world game about an outlaw baker searching for freedom between saloons, trains, and dusty frontier towns. Players ride horses, hunt, rob trains, bake legendary bread, and decide whether to become a local hero or the biggest problem in the county. Its strongest parts are the slow pace, detailed world, and story about loyalty, guilt, and one last chance.', 34.99, 59.99, 42, 'Red Bread Redemption cover art', 'assets/images/games/red-bread-redemption.jpg', 'Open World', 'Western', 4.7, 'PEGI 18', 'PC, PlayBox Series, X-Cube', 'Rocky Trail Games', 'Frontier Softworks', '2022-06-10', 88, 1, 0),
('Cyberpunk 2076: Bugfix City', 'cyberpunk-2076-bugfix-city', 'A neon RPG about implants, corporations, street gangs, and a night city where every patch changes the future. Create your own mercenary, upgrade your body with technology, and solve quests through hacking, dialogue, stealth, or direct combat. The city feels dirty, alive, and full of contrast between luxury advertising and people trying to survive.', 29.99, 59.99, 50, 'Bugfix City cover art', 'assets/images/games/cyberpunk-2076-bugfix-city.jpg', 'RPG', 'Sci-Fi', 4.3, 'PEGI 18', 'PC, PlayBox Series, X-Cube', 'CD Rework Project', 'Neon Patch Publishing', '2023-12-05', 70, 0, 0),
('God of Chores: Dadnarok', 'god-of-chores-dadnarok', 'A mythological action adventure about an angry father, his son, and a suspicious number of household duties during the end of the world. Expect cinematic combat, puzzles, equipment upgrades, and character conversations that give the action more emotional weight. The game mixes epic northern mythology with a personal story about family, control, and carrying groceries home.', 52.99, 69.99, 24, 'Dadnarok cover art', 'assets/images/games/god-of-chores-dadnarok.jpg', 'Action Adventure', 'Mythology', 4.8, 'PEGI 18', 'PC, PlayBox Series', 'Santa Monica-ish Studio', 'Nine Realms Games', '2024-04-26', 60, 1, 0),
('Poket Monsters: Violet-ish', 'poket-monsters-violet-ish', 'Collect small battle creatures, train them, and explore an open school region filled with strange professors and colorful rivals. The game combines turn-based battles, creature trading, picnic cooking, and gradual exploration of new areas at your own pace. It is best for players who love completing collections and building the perfect team for each challenge.', 41.99, 59.99, 30, 'Violet-ish cover art', 'assets/images/games/poket-monsters-violet-ish.jpg', 'Monster Taming', 'RPG', 4.0, 'PEGI 7', 'PC, Nintendo-style handheld', 'Tiny Beast Factory', 'Pocket-ish Publishing', '2024-11-22', 135, 0, 0),
('Resident Weevil: Village Market', 'resident-weevil-village-market', 'A survival horror game set in a suspicious village full of locked doors, herbs, strange merchants, and terrible noises around every corner. Players must save ammunition, solve mechanical puzzles, search for keys, and decide when to fight or run. The tension comes from slow exploration, dangerous timing, and the uneasy atmosphere of an old market after dark.', 36.99, 49.99, 26, 'Village Market cover art', 'assets/images/games/resident-weevil-village-market.jpg', 'Horror', 'Survival', 4.5, 'PEGI 18', 'PC, PlayBox Series, X-Cube', 'Capybarrel Studio', 'Umbra Door Games', '2023-10-13', 45, 0, 0),
('Hollow Evening: Bug Song', 'hollow-evening-bug-song', 'A hand-drawn metroidvania set in an underground insect kingdom full of secrets, difficult jumps, and melancholic music. Exploration is built around earning new abilities that let you return to old places and open them in new ways. The game offers tough combat, beautiful atmosphere, and a quiet story assembled from small encounters and symbols.', 14.99, 19.99, 25, 'Bug Song cover art', 'assets/images/games/hollow-evening-bug-song.jpg', 'Metroidvania', 'Indie', 4.9, 'PEGI 7', 'PC, Console, Handheld', 'Tiny Needle Team', 'Cavern Echoes', '2022-02-24', 210, 1, 0),
('Animal Crossing-ish: Cozy Island', 'animal-crossing-ish-cozy-island', 'A relaxing social life simulation on an island where you collect decorations, catch fish, talk to neighbors, and slowly pay off a suspiciously friendly shopkeeper. Every day brings visitors, seasonal items, conversations, and new ways to shape the island around your mood. It is a slow and cozy game for players who want to relax, collect, and build a small virtual home.', 32.99, 44.99, 27, 'Cozy Island cover art', 'assets/images/games/animal-crossing-ish-cozy-island.jpg', 'Life Sim', 'Cozy', 4.6, 'PEGI 3', 'PC, Nintendo-style handheld', 'Soft Leaf Studio', 'Cozy Cart Publishing', '2025-03-28', 160, 0, 1),
('Doomed Eternal-ish', 'doomed-eternal-ish', 'A brutal arena FPS where the music is loud and most problems can be solved with a chainsaw. The game pushes players to keep moving, swap weapons, use vertical arenas, and stay aggressive to survive. It is fast, heavy, exaggerated, and at its best when the screen becomes controlled chaos.', 22.99, 39.99, 43, 'Doomed Eternal-ish cover art', 'assets/images/games/doomed-eternal-ish.jpg', 'FPS', 'Arena Shooter', 4.6, 'PEGI 18', 'PC, PlayBox Series, X-Cube', 'id-ish Forge', 'Mars Gate Publishing', '2022-12-16', 95, 0, 0),
('Stardew Vally-ish', 'stardew-vally-ish', 'A farming indie simulation about growing crops, mining, building friendships, and escaping a soulless office job. You begin with an abandoned farm and slowly turn it into a thriving place full of animals, machines, handmade goods, and people from the nearby town. The game feels simple at first, but each day gives you a small goal and a satisfying sense of progress.', 11.99, 14.99, 20, 'Stardew Vally-ish cover art', 'assets/images/games/stardew-vally-ish.jpg', 'Farming Sim', 'Indie', 4.8, 'PEGI 7', 'PC, Console, Mobile', 'Concerned Farmer', 'Harvest Byte', '2021-05-07', 250, 1, 0),
('Assassin''s Creed-ish: Velvet Hood', 'assassins-creed-ish-velvet-hood', 'A historical stealth action game with rooftop parkour, secret orders, and a hood that takes the wind very seriously. Players track targets, blend into crowds, upgrade equipment, and uncover conspiracies between powerful families. The city is designed for vertical movement, quiet approaches, and moments where a careful plan becomes an improvised escape across the rooftops.', 27.99, 49.99, 44, 'Velvet Hood cover art', 'assets/images/games/assassins-creed-ish-velvet-hood.jpg', 'Stealth', 'Action Adventure', 4.2, 'PEGI 18', 'PC, PlayBox Series, X-Cube', 'Ubi-ish Towers', 'Hidden Blade Media', '2023-07-14', 80, 0, 0),
('Rocket League-ish: Turbo Ball', 'rocket-league-ish-turbo-ball', 'A sports racing game where rocket-powered cars play football in arenas filled with boosts, flips, and goals that look easy until you try them. It offers short online matches, training modes, vehicle cosmetics, and ranked leagues for competitive players. The rules are simple, but the control skill ceiling makes it great for both quick parties and long-term improvement.', 17.99, 24.99, 28, 'Turbo Ball cover art', 'assets/images/games/rocket-league-ish-turbo-ball.jpg', 'Sports', 'Racing', 4.4, 'PEGI 3', 'PC, Console', 'Psyon-ish Motors', 'Boost Arena Games', '2024-06-21', 190, 0, 0)
ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    description = VALUES(description),
    price = VALUES(price),
    original_price = VALUES(original_price),
    discount_percent = VALUES(discount_percent),
    image_title = VALUES(image_title),
    image_url = VALUES(image_url),
    genre = VALUES(genre),
    secondary_genre = VALUES(secondary_genre),
    rating = VALUES(rating),
    age_rating = VALUES(age_rating),
    platform = VALUES(platform),
    developer = VALUES(developer),
    publisher = VALUES(publisher),
    release_date = VALUES(release_date),
    stock = VALUES(stock),
    is_featured = VALUES(is_featured),
    is_new_release = VALUES(is_new_release);
